export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNIQUE_CONSTRAINT = 'UNIQUE_CONSTRAINT',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  FORBIDDEN = 'FORBIDDEN',
}
